### ISSUE TITLE
Versão do projeto EA?

### ISSUE THREAD

**Issue by santos-fernando** [jcbebr/KingChat-projeto#1]
Não consegui abrir o projeto EA. Favor salvar como em uma versão que a UDESC/CEAVI possui licença e fazer push. Apenas ao conseguir abrir o diagrama é que poderei avaliar e atribuir uma nota. Favor avisar respondendo esta issue assim que o push for feito.

**Comment by jcbebr** [comment]
O EA é retro compatível com suas versões anteriores. 
https://www.sparxsystems.com/forums/smf/index.php?topic=30107.0

O projeto foi feito na versão de avaliação, pois o software é pago e até onde eu sei a UDESC não disponibiliza a licença para uso pessoal. Além disso somente em alguns laboratórios está instalado, por esse motivo não foi testado.

Fiz o push dos Diagramas em imagens caso não consiga abrir o projeto.

**Comment by santos-fernando** [comment]
Em meu laptop tenho instalado o EA versão 8.0 e ele não reconhece o projeto com a extensão .eapx. Na segunda-feira a tarde tentarei abrir o projeto no computador da UDESC para verificar. 

Sobre o EA no laboratório 5, o pessoal do NTI me garantiu que está instalado. Na segunda-feira a tarde vou pedir para o monitor Tiago verificar.

Fiz a correção desta etapa a partir das imagens dos diagramas. Vou postar a correção em uma outra issue.

**Comment by santos-fernando** [comment]
Apenas para informar que tentei abrir o projeto no EA da UDESC (versão 10, agora foi instalado no laboratório 5) e ainda assim não é possível abrir. Nesta quarta-feira a tarde peça para o Denilson me mostrar o projeto rodando no EA de algum computador aqui do laboratório da UDESC.  Veja na imagem o erro ao tentar abrir o projeto. 

![erro-abrir-projeto-ea](https://user-images.githubusercontent.com/46003944/68722396-13943480-0594-11ea-9fc6-1a1e77b4bcf3.png)
